"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

export function AutoThread({ reportId }: { reportId: number }) {
  const [text, setText] = useState<string | null | undefined>(undefined);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    api.getThread(reportId).then((r) => setText(r.text)).catch(() => setText(null));
  }, [reportId]);

  if (text === undefined) return null;
  if (!text || !text.trim()) return null;

  async function copy() {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* ignore */
    }
  }

  return (
    <div className="card">
      <div className="byline" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span>Auto-thread</span>
        <button onClick={copy} style={{ padding: "3px 12px", fontSize: 12 }}>
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <p className="muted" style={{ fontSize: 12, marginTop: 0 }}>
        5-tweet distillation generated by the editor. Paste into X / LinkedIn.
      </p>
      <pre
        style={{
          whiteSpace: "pre-wrap", fontSize: 13,
          fontFamily: "inherit",
          background: "var(--forte-bg)", padding: 12, borderRadius: 4,
          margin: 0,
        }}
      >
        {text}
      </pre>
    </div>
  );
}
